version: '3.9'

services:

  ollama:
    env_file: .env
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "${OLLAMA_PORT}:${OLLAMA_PORT}"
    volumes:
      - ollama_models:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${OLLAMA_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  openwebui:
    env_file: .env
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    ports:
      - "${OPENWEBUI_PORT}:${OPENWEBUI_PORT}"
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_API_URL=http://ollama:${OLLAMA_PORT}
    volumes:
      - openwebui_data:/app/backend/data
    restart: unless-stopped

volumes:
  ollama_models:
  openwebui_data: